language: swift
dist: artful
install:
  - sudo apt-get --yes install libavcodec-dev libavcodec57 libavformat-dev libavformat57 libavresample-dev libavresample3 libavutil-dev libavutil55 libswresample-dev libswresample2 libswscale-dev libswscale4
xcode_project: pupil.xcodeproj
script:
  - swift build
  - swift test
